# Generated by Django 2.2.2 on 2019-06-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190617_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogs',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasklogs',
            name='date_finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklogs',
            name='time_active',
            field=models.FloatField(null=True),
        ),
    ]
